"""Device-specific neurotechnology evidence; preserve original UNKNOWN fields."""
from pathlib import Path
import csv,json,hashlib
ROOT=Path(__file__).resolve().parents[3];OUT=Path(__file__).resolve().parent
TABLES=ROOT/'Reference/tables/15_official_evidence_20261007_b05'
csv.field_size_limit(16*1024*1024)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):
    with p.open(encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def write(name,rows,folder=TABLES):
    with (folder/name).open('w',encoding='utf-8-sig',newline='') as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
assert not TABLES.exists(),'Use a new batch'
baseline=[]
for folder in ['10_global_technology_iso249_20261006_b04','11_official_evidence_20261007_b01','12_official_evidence_20261007_b02','13_official_evidence_20261007_b03','14_official_evidence_20261007_b04']:
    baseline.extend((ROOT/'Reference/tables'/folder).glob('*.csv'))
baseline.append(ROOT/'reports/2026-10-07/evidence_integration/global_registry_evidence_query.sqlite')
manifest=[dict(path=p.relative_to(ROOT).as_posix(),sha256=sha(p)) for p in baseline]
orgs={r['entity_id']:r for r in read(ROOT/'Reference/tables/10_global_technology_iso249_20261006_b04/registry_global_organizations.csv')}
assert all(e in orgs for e in ['GTO0033','GTO0034','GTO0035'])
TABLES.mkdir(parents=True)
pages=[('OEB05S01','FDA','https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfPMN/pmn.cfm?ID=K242618','Decision Date; Device Name','REGULATOR_DATABASE'),('OEB05S02','FDA / Precision Neuroscience submitted summary','https://www.accessdata.fda.gov/cdrh_docs/pdf24/K242618.pdf','PDF pp.1,4,6; clearance letter, indications, device description','REGULATOR_LETTER_AND_APPLICANT_SUMMARY'),('OEB05S03','Neuralink','https://www.neuralinktrials.com/trials/device-control','PRIME; CONVOY','PROVIDER_OFFICIAL_WEBSITE'),('OEB05S04','Synchron','https://synchron.com/technology','Stentrode; investigational caution','PROVIDER_OFFICIAL_WEBSITE'),('OEB05S05','Synchron','https://synchron.com/join','INTENT; FOCUS; disclaimer','PROVIDER_OFFICIAL_WEBSITE')]
sources=[dict(source_id=s,publisher=p,url=u,locator=l,source_type=k,read_on='2026-10-07',access_state='WEB_TOOL_TEXT_READ',raw_http_archive='NOT_ARCHIVED',license_state='UNKNOWN') for s,p,u,l,k in pages]
facts=[('OEB05C01','GTO0035','OEB05S01','FDA 記錄 Layer 7-T、申請人 Precision Neuroscience, Corp.、K242618 及 2025-03-30 的實質等同決定。','REGULATOR_DEVICE_SPECIFIC_DECISION'),('OEB05C02','GTO0035','OEB05S02','Layer 7-T 適用於少於 30 天的皮質表面電訊號記錄、監測及刺激。','REGULATOR_DEVICE_SPECIFIC_INDICATIONS'),('OEB05C03','GTO0035','OEB05S02','申請人摘要描述 Layer 7-T 為被動器件，無無線功能及軟件。','REGULATOR_HOSTED_APPLICANT_DEVICE_DESCRIPTION'),('OEB05C04','GTO0033','OEB05S03','Neuralink 頁稱 N1 已用於人體研究；本批記為提供方自述，未取得試驗結果驗證。','PROVIDER_REPORTED_HUMAN_STUDY'),('OEB05C05','GTO0033','OEB05S03','Neuralink 頁列 PRIME NCT06429735 及 CONVOY NCT06710626，描述 N1 控制外部設備及輔助機械臂研究。','PROVIDER_TRIAL_LISTING_ONLY'),('OEB05C06','GTO0034','OEB05S04','Synchron 描述 Stentrode 為血管內植入 BCI，並標示研究用途器件。','PUBLIC_DESCRIPTION_ONLY'),('OEB05C07','GTO0034','OEB05S05','Synchron 頁列 INTENT NCT07543367、FOCUS NCT07533903，並自述系統未獲商業使用批准。','PROVIDER_TRIAL_AND_REGULATORY_DESCRIPTION_ONLY')]
claims=[dict(claim_id=c,entity_id=e,source_id=s,claim=t,evidence_state='VERIFIED',verification_scope=v,reviewed_on='2026-10-07',identity_link_state='DEVICE_OR_PROVIDER_NAME_CONTEXT_NOT_LEGAL_REGISTRATION',performance_state='UNKNOWN',deployment_state='UNKNOWN',regulatory_state='DEVICE_SPECIFIC_510K_SE_DECISION' if c=='OEB05C01' else 'SEE_SCOPED_CLAIM_NOT_COMPANY_WIDE',world_frontier_rank_state='UNKNOWN',training_permission='UNKNOWN') for c,e,s,t,v in facts]
neuro=[dict(neuro_supplement_id='OEB05N01',entity_id='GTO0033',product_name='N1 Implant',invasiveness='IMPLANTED_PROVIDER_DESCRIPTION',modality='UNKNOWN',direction='READ_TO_DEVICE_CONTROL_PROVIDER_DESCRIPTION',direction_scope='PUBLIC_GOAL_NOT_ALL_THOUGHT_CONTENT',wireless_state='UNKNOWN_THIS_BATCH',remote_neural_access='UNKNOWN',information_bandwidth='UNKNOWN',human_trial_state='HUMAN_USE_PROVIDER_REPORTED',clinical_phase='UNKNOWN_REGISTRY_NOT_READ',regulatory_state='INVESTIGATIONAL_PROVIDER_DESCRIPTION_NOT_MARKETING_CLEARANCE',country_capability_level='UNKNOWN',supporting_claim_ids='OEB05C04;OEB05C05'),dict(neuro_supplement_id='OEB05N02',entity_id='GTO0034',product_name='Stentrode',invasiveness='INVASIVE_ENDOVASCULAR_PROVIDER_DESCRIPTION',modality='UNKNOWN_THIS_BATCH',direction='READ_TO_DEVICE_CONTROL_PROVIDER_DESCRIPTION',direction_scope='MOVEMENT_INTENT_PROVIDER_DESCRIPTION',wireless_state='UNKNOWN_THIS_BATCH',remote_neural_access='UNKNOWN',information_bandwidth='UNKNOWN',human_trial_state='TRIALS_PROVIDER_LISTED',clinical_phase='UNKNOWN_REGISTRY_NOT_READ',regulatory_state='INVESTIGATIONAL_NO_COMMERCIAL_APPROVAL_PROVIDER_DESCRIPTION',country_capability_level='UNKNOWN',supporting_claim_ids='OEB05C06;OEB05C07'),dict(neuro_supplement_id='OEB05N03',entity_id='GTO0035',product_name='Layer 7-T',invasiveness='INVASIVE_CORTICAL_SURFACE',modality='ECoG_ARRAY_DEVICE_DESCRIPTION',direction='RECORD_MONITOR_STIMULATE',direction_scope='LABELLED_ELECTRICAL_FUNCTION_NOT_SEMANTIC_MIND_WRITE',wireless_state='NO_WIRELESS_DEVICE_ITSELF_APPLICANT_SUMMARY',remote_neural_access='UNKNOWN_EXTERNAL_SYSTEM',information_bandwidth='UNKNOWN',human_trial_state='UNKNOWN_THIS_BATCH',clinical_phase='NOT_INFERRED_FROM_510K',regulatory_state='K242618_510K_SE_2025_03_30_LESS_THAN_30_DAYS',country_capability_level='UNKNOWN',supporting_claim_ids='OEB05C01;OEB05C02;OEB05C03')]
trials=[dict(trial_link_id=f'OEB05L{i:02}',entity_id=e,provider_trial_name=n,nct_id=k,provider_country_label=country,supporting_claim_id=c,verification_scope='PROVIDER_LISTING_ONLY',registry_record_read_state='NOT_SUCCESSFULLY_READ',registry_current_status='UNKNOWN',clinical_phase='UNKNOWN',actual_enrollment='UNKNOWN',results_state='NOT_VERIFIED_THIS_BATCH') for i,(e,n,k,c,country) in enumerate([('GTO0033','PRIME','NCT06429735','OEB05C05','US_PROVIDER_ELIGIBILITY_CONTEXT'),('GTO0033','CONVOY','NCT06710626','OEB05C05','NOT_SEPARATELY_VERIFIED'),('GTO0034','INTENT','NCT07543367','OEB05C07','US_PROVIDER_LISTING'),('GTO0034','FOCUS','NCT07533903','OEB05C07','AU_PROVIDER_LISTING')],1)]
attempts=[dict(url='https://clinicaltrials.gov/study/'+n,result='WEB_TOOL_HTML_SHELL_NO_PROTOCOL_CONTENT',use='NOT_VERIFIED_REGISTRY_STATUS') for n in ['NCT06429735','NCT05035823']]+[dict(url='https://clinicaltrials.gov/api/v2/studies/'+n,result='LOCAL_REQUEST_CONNECTION_REFUSED_WINERROR_10061',use='NOT_VERIFIED_REGISTRY_STATUS') for n in ['NCT06429735','NCT05035823','NCT07543367','NCT07533903']]+[dict(url='https://pubmed.ncbi.nlm.nih.gov/41040697/',result='WEB_TOOL_INTERNAL_ERROR',use='SEARCH_LEAD_ONLY_NOT_PAPER_VERIFICATION')]
write('registry_supplemental_sources.csv',sources);write('registry_supplemental_claims.csv',claims);write('registry_neurotechnology_supplement.csv',neuro);write('registry_trial_links.csv',trials);write('access_attempts.csv',attempts,OUT);write('baseline_manifest.csv',manifest,OUT)
assert {r['source_id'] for r in claims}<={r['source_id'] for r in sources}
assert {r['supporting_claim_id'] for r in trials}<={r['claim_id'] for r in claims}
for r in neuro:assert set(r['supporting_claim_ids'].split(';'))<={r['claim_id'] for r in claims}
assert all(r['registry_current_status']=='UNKNOWN' for r in trials)
for r in manifest:assert sha(ROOT/r['path'])==r['sha256']
result=dict(pass_check=True,sources=5,claims=7,device_profiles=3,provider_trial_links=4,successful_registry_protocol_reads=0,prior_batches_and_query_snapshot_unchanged=True,regulatory_decision_scope='Layer 7-T K242618 only',new_country_capability_levels=0,new_rankings=0)
(OUT/'validation.json').write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps(result))
